### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [deni2312/InstagramAPI#1]
Is it possible to get post information, from a public page such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

without login?

**Comment by deni2312** [comment]
No, with current version it's impossible without login, but with the reversing of the endpoint it's possible to find the media_id and download the photo with returned json.

**Comment by 89z** [comment]
what do you mean by "with returned json"?

**Comment by deni2312** [comment]
I mean that you'll get the url of the media in a json format.

**Comment by 89z** [comment]
I looked into this for several days, I dont think what youre saying is possible. From what I can tell, even "reversing the endpoint" still requires authentication. If someone can prove me wrong, I would be happy about that

**Comment by deni2312** [comment]
I mean public endpoints, otherwise how can you retreive photos from your browser? The unique way is to reverse the public endpoint, try with a proxy like mitmproxy.

**Comment by 89z** [comment]
> I mean public endpoints, otherwise how can you retreive photos from your browser? The unique way is to reverse the public endpoint, try with a proxy like mitmproxy.

I dont see why MitmProxy would be needed, couldnt someone just look at the network tab in web console?

**Comment by deni2312** [comment]
No, cause it's all'under https and headers, body are encrypted

**Comment by 89z** [comment]
I dont think what you are saying is true. I just captured this now with the browser:

~~~
GET /graphql/query/?query_hash=8c2a529969ee035a5063f2fc8602a0fd&variables=%7B%22id%22%3A%22294582047%22%2C%22first%22%3A12%7D HTTP/1.1
Host: www.instagram.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Referer: https://www.instagram.com/p/CT-cnxGhvvO/
X-CSRFToken: nsJlLA43MPhfBfLp2aUpfmF6kdHquppo
X-IG-App-ID: 936619743392459
X-ASBD-ID: 198387
X-IG-WWW-Claim: 0
X-Requested-With: XMLHttpRequest
Connection: keep-alive
~~~

and I can see the full response, with no encryption.

**Comment by deni2312** [comment]
You're seeing graphql, that's a public endpoint of Instagram about official api, obviously it's not encrypted, the link of the photo is retrieved by the hidden endpoint, try with mitmproxy and you'll understand what i'm saying

**Comment by 89z** [comment]
Nope, I just tried again with MitmProxy, and I didnt see any addition requests beyond what I saw in the browser web console.

**Comment by deni2312** [comment]
Strange i get all endpoints with mitmproxy, in next implementations i'll add support to retreive photos without login, you can contact me on telegram for any issue, i'll close this.

**Comment by 89z** [comment]
Can you post an example request that you are seeing? That way I can just implement it myself...

**Comment by 89z** [comment]
Since you provided no proof (or even evidence) of any of your claims, I went ahead and made my own implementation:

https://github.com/89z/mech/tree/master/instagram

If you are able to give more info about these "hidden APIs" it would be appreciated, but otherwise I am moving on.

**Comment by deni2312** [comment]
Yes, they aren't hidden, but only not public api, i simulate with headers the request of a random phone, i'll integrate your endpoint to get the image
